name: sqflite_web
homepage: https://github.com/FunnyLabz/sqflite_web
description: sqflite web implementation (without database persistency)
version: 1.1.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: SqflitePluginWeb
        fileName: sqflite_web.dart

  # TODO: Those assets should only be on Web platform but this is not yet handled by Flutter
  # https://github.com/flutter/flutter/issues/8230
  assets:
    - packages/sqflite_web/assets/require.js
    - packages/sqflite_web/assets/sqflite_web.js

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  plugin_platform_interface: ^1.0.1

  # For Sqflite 'subplugin' compatibility
  sqflite_common: ^2.0.0+2
  synchronized: '>=2.0.2 <4.0.0'
  path: '>=1.5.1 <3.0.0'
  meta: '>=1.1.8 <3.0.0'

  # For Web implementation compatibility
  js: ^0.6.2

dev_dependencies:
  pedantic:
  test:
  process_run: '>=0.10.7'
